Disable siso on mac
Siso doesn't work on the old version of mac os we use on CI.

It gets:
```
dyld: Symbol not found: _SecTrustCopyCertificateChain
  Referenced from: /Volumes/Android/buildbot/src/googleplex-android/main-build-tools/prebuilts/siso/darwin-x86/siso (which was built for Mac OS X 12.0)
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Volumes/Android/buildbot/src/googleplex-android/main-build-tools/prebuilts/siso/darwin-x86/siso
```

Bug: 490162844
Test: Presubmits
Change-Id: Id9ee91ed94223a69219be3ee3d383363dc39b6cf