Raise default kotlin language version to 2
RELEASE_KOTLIN_LANG_VERSION is enabled everywhere, raise the default
kotlin language version to 2 so that the integration tests (which
don't have all the build flags) don't fail on -Werror -language-version 1.9:
warning: language version 1.9 is deprecated and its support will be removed in a future version of K
otlin
error: warnings found and -Werror specified

Test: presubmit
Change-Id: Id0f3e2cceebf2672569bbd623ee505f5adb99a83